//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.DoctorModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctors_specialization
    {
        public int id { get; set; }
        public int doctor_id { get; set; }
        public int specialization_id { get; set; }
        public string specialization_name { get; set; }
    
        public virtual doctor doctor { get; set; }
    }
}
