//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.DoctorModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public doctor()
        {
            this.doctors_contacts = new HashSet<doctors_contacts>();
            this.doctors_department = new HashSet<doctors_department>();
            this.doctors_specialization = new HashSet<doctors_specialization>();
        }
    
        public int id { get; set; }
        public int doctor_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string mob_room { get; set; }
        public string display_name { get; set; }
    
        public virtual ICollection<doctors_contacts> doctors_contacts { get; set; }
        public virtual ICollection<doctors_department> doctors_department { get; set; }
        public virtual ICollection<doctors_specialization> doctors_specialization { get; set; }
    }
}
