//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.ValidationModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserTypesEntities : DbContext
    {
        public UserTypesEntities()
            : base("name=UserTypesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<validate_patient> validate_patient { get; set; }
        public virtual DbSet<validatedoctor> validatedoctors { get; set; }
        public virtual DbSet<validateemployee> validateemployees { get; set; }
    }
}
