//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.ValidationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class validate_patient
    {
        public string hospital_number { get; set; }
        public System.DateTime date_of_birth { get; set; }
    }
}
