//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.EmployeeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_employment_details
    {
        public System.Guid employment_details_id { get; set; }
        public System.Guid employee_id { get; set; }
        public string employee_nr { get; set; }
        public string old_employee_id { get; set; }
        public string display_name { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<System.DateTime> effective_from_date { get; set; }
        public Nullable<System.DateTime> effective_until_date { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public string termination_reason { get; set; }
        public string occupation { get; set; }
        public string occupation_status { get; set; }
        public string occupation_type { get; set; }
        public string employee_status { get; set; }
        public string employee_type { get; set; }
        public string company_code { get; set; }
        public string company { get; set; }
        public string job_type { get; set; }
        public Nullable<int> job_type_level_nr { get; set; }
        public string job_category { get; set; }
        public string job_title { get; set; }
        public string job_grade { get; set; }
        public Nullable<int> job_grade_level_nr { get; set; }
        public string costcentre { get; set; }
        public string department { get; set; }
        public string position_status { get; set; }
        public string employment_reason { get; set; }
        public string work_hours_per_week { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
