//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.EmployeeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_education
    {
        public System.Guid education_id { get; set; }
        public System.Guid employee_id { get; set; }
        public string employee_nr { get; set; }
        public string display_name { get; set; }
        public string major { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> dates_attended_from { get; set; }
        public Nullable<System.DateTime> dates_attended_to { get; set; }
        public Nullable<System.DateTime> graduation_date { get; set; }
        public string comments { get; set; }
        public Nullable<bool> verified_flag { get; set; }
        public Nullable<System.DateTime> verified_date { get; set; }
        public Nullable<bool> completed_flag { get; set; }
        public string education_type { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
