//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.EmployeeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.employee_career_history = new HashSet<employee_career_history>();
            this.employee_education = new HashSet<employee_education>();
            this.employee_employment_details = new HashSet<employee_employment_details>();
            this.employee_privileges = new HashSet<employee_privileges>();
        }
    
        public System.Guid employee_id { get; set; }
        public string employee_nr { get; set; }
        public string old_employee_id { get; set; }
        public string display_name { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string common_name { get; set; }
        public string title { get; set; }
        public string suffix { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string race { get; set; }
        public string nationality { get; set; }
        public string religion { get; set; }
        public string marital_status { get; set; }
        public string primary_language { get; set; }
        public string ethnic_group { get; set; }
    
        public virtual ICollection<employee_career_history> employee_career_history { get; set; }
        public virtual ICollection<employee_education> employee_education { get; set; }
        public virtual ICollection<employee_employment_details> employee_employment_details { get; set; }
        public virtual ICollection<employee_privileges> employee_privileges { get; set; }
    }
}
