//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.PatientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_deposit_balance
    {
        public System.Guid customer_id { get; set; }
        public Nullable<decimal> deposit_amount { get; set; }
        public Nullable<decimal> used_amount { get; set; }
    
        public virtual patient_visit patient_visit { get; set; }
    }
}
