//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Models.PatientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_visit
    {
        public patient_visit()
        {
            this.patient_items_used = new HashSet<patient_items_used>();
        }
    
        public System.Guid patient_id { get; set; }
        public System.Guid patient_visit_id { get; set; }
        public System.DateTime actual_visit_date_time { get; set; }
        public string hospital_number { get; set; }
        public Nullable<System.DateTime> closure_date_time { get; set; }
    
        public virtual patient_deposit_balance patient_deposit_balance { get; set; }
        public virtual ICollection<patient_items_used> patient_items_used { get; set; }
    }
}
